title: TSG Machine Learning
email: levelfourslv@gmail.com
description: >
  TSG Machine Learning Substudy Group in 2015
baseurl: "/ml2015"
url: "http://tsg.ne.jp/"
twitter_username: tsg_ut
github_username:  tsg-ut

markdown: kramdown
exclude: ["README.md"]
